// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// In Docker, dotenv is not needed as env vars are passed directly
if (process.env.NODE_ENV !== 'production') {
  try {
    require('dotenv/config');
  } catch (e) {
    // dotenv not available or .env file doesn't exist - use environment variables directly
  }
}

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL || process.env["DATABASE_URL"],
  },
});
